### ISSUE TITLE
allow + render markdown between lines

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [dominiczaq/obsidian-plugin-time-diff#1]
currently a timediff block is rendered as just raw text

i'd like to include checkboxes/bullet lists between the items

like 
```
`` `timediff

10:00  - 11:00
* [some-meeting](link torecording)
* [workitem 1234](jira card)

13:00 -15:00
* [ ] todo item
* [x] even more
`` `
```

**Comment by dominiczaq** [comment]
I think the easiest way would be to reformat your makrdown as below:
```
` ``timediff
10:00 - 11:00
` ``
* [some-meeting](link torecording)
* [workitem 1234](jira card)

` ``timediff
13:00 - 15:00
` ``
* [ ] todo item
* [x] even more
```

wdyt?

**Comment by RonnyPfannschmidt** [comment]
Then each block would get a own total
 So not fun

I wonder if there is any other way to do this

**Comment by DanMundy** [comment]
There's the command "timediff-total" which adds them all up, but only shows the total briefly.

I wonder if we could have some way of displaying that total on the page?

Then you could have several blocks on the page (which would be useful for other reasons too" 
but still easily show the total time spent.

**Comment by dominiczaq** [comment]
@RonnyPfannschmidt I don't think it's possible while using ```  syntax as it parses whole content inside as code. I'm open to suggestions how this could be implemented though.

**Comment by dominiczaq** [comment]
@DanMundy do you have suggestion where to display it? Maybe in status bar? https://marcus.se.net/obsidian-plugin-docs/user-interface/status-bar

Preferably this should be a separate issue, do you mind creating one?

**Comment by dominiczaq** [comment]
Closing as stale, please reopen if necessary
