### ISSUE TITLE
Add how-to to Readme explaining how to start a timediff block

### ISSUE THREAD

**Issue by jkfm** [dominiczaq/obsidian-plugin-time-diff#2]
Hi,

thanks for providing this plugin! It probably seems very basic, but for me it'd have helped to provide a basic sentence telling me that I need to start a block like this:

\```timediff
...
\```

because for me it was not obvious. 

Can do a PR if you want. 

Regards,
Johannes

**Comment by dominiczaq** [comment]
Hi! Thank you for your feedback.

I've added example how to render timediff block, so it should be clearer now.

**Comment by jkfm** [comment]
Thanks so much!
